In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
zeros_array = np.zeros((2, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
ones_array = np.ones((4, 4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
import numpy as np
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [5]:
import numpy as np
random_array = np.random.randn(5, 5)
print(random_array)

[[ 0.21492177 -0.59344757  1.89546086 -2.11445072 -0.34413441]
 [ 1.03301966  0.07461871  0.65226859  0.92349915  1.12733215]
 [-0.74093695  0.85054516 -1.68364052  0.47171007  1.07015442]
 [-0.48417845  0.54684037 -0.09634686  1.23247435 -0.43222555]
 [-1.19881017 -1.33237502 -0.10230434 -0.42980082 -0.54563748]]


In [8]:
import numpy as np
array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15]])
print("Array:\n", array_2d)
print("Shape:", array_2d.shape)
print("Number of dimensions:", array_2d.ndim)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Shape: (3, 5)
Number of dimensions: 2


In [6]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [7]:
import numpy as np
arr = np.arange(10, 60, 10)
print(arr[1:4])

[20 30 40]


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr[arr > 3]
print(new_arr)

[4 5 6]


In [10]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum_array = a + b
print(sum_array)

[5 7 9]
